config/routes.rb
NastavljaSe::Application.routes.draw do

  
  resources :games, :only => [:index, :create, :new, :show] do
    resources :sequels, :only => [:create, :new]
  end

  root :to => "home#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to  :sequel
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :sequels
  
  validates_presence_of	:title
end

app/models/sequel.rb
class Sequel < ActiveRecord::Base
  has_many  :comments
  belongs_to  :game
  
  has_attached_file :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @current_games = Game.all
    respond_to do |format|
      format.html
    end 
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
		@game = Game.new
  end
  
  def create
  	@game = Game.new(params[:game])
  	if @game.save
  		redirect_to @game
  	else
  		render :action => :new
  	end	
  end
  
  def show
		@game = Game.find(params[:id])
  end
  
  def index
  	@games = Game.all
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @current_games = Game.all
    respond_to do |format|
      format.html
    end 
  end

end

app/controllers/sequels_controller.rb
class SequelsController < ApplicationController

  def new
    @game = Game.find(params[:game_id])
		@sequel = Sequel.new
  end
  
  def create
  	@sequel = Sequel.new(params[:sequel])
  	@sequel.game_id = params[:game_id]
  	@sequel.save	
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<h1> Izlistaj svih igara </h1>

<% @games.each do |g| %>
<p>
	<%= link_to g.title, game_path(g) %> 
	<% if g.sequels.count == 0 %>
		<%= link_to "Delete game", "#" %>
	<% end %>
</p>
	
<% end %>

app/views/games/new.html.erb
<h1> Stvori igru </h1>

<%= form_for @game do |f| %>

<% if @game.errors.any? %>
  <%= @game.errors %>
<% end %>
 
<p>
<%= f.label :title %>
<%= f.text_field :title %>
</p>

<p>
<%= f.label	:description %>
<%= f.text_area	:description, :size => "30x5" %>
</p>

<p>
<%= f.label	:type	%>
<%= f.select :type_id, [["Tip: linija", 1], ["Tip: unutrag", 2], ["Tip: stablo", 3]] %>
</p>

<% end %>

app/views/games/show.html.erb
<h1><%= @game.title %></h1>

Ovdje ide opis igre: <%= @game.description %>


<%= link_to "Nastavi!", new_game_sequel_path(@game) %>

<% @game.sequels.each do |sequel| %>
  <h3> <%= sequel.created_at %> </h3>
  <%= image_tag sequel.image.url %>
<% end %>
    

app/views/home/index.html.erb
Naslovna stranica

<% @current_games.each do |game| %>
  <div><%= game.title %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NastavljaSe</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sequels/new.html.erb
<h1> Nastavljanje </h1>

<%= form_for [@game, @sequel], :html => { :multipart => true } do |form| %>
  <%= form.file_field :image %>
  <%= form.submit "Pošalji"%>
<% end %>